probando archivos excluidos del coverage

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -100,36 +100,26 @@ jobs:
       - run: npm install
       - run: npm run test
       - sonarcloud/scan
+      - run:
+          name: Verificar calidad de SonarCloud
+          command: |
+            STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$SONAR_PROJECT_KEY" | jq -r '.projectStatus.status')
+            if [ "$STATUS" != "OK" ]; then
+              echo "Quality gate failed: $STATUS"
+              exit 1
+            else
+              echo "Quality gate passed: $STATUS"
+            fi
       - slack/notify:
           channel: facultad
           event: fail
           template: basic_failed
-          custom: '{"text":"Análisis de SonarCloud ha fallado! :x:"}'
+          custom: '{"text":"No se ha pasado el análisis de SonarCloud! :x:"}'
       - slack/notify:
           channel: facultad
           event: pass
           template: basic_success
-          custom: '{"text":"Análisis de SonarCloud completado! :white_check_mark:"}'
-
-  # sonarcloud:
-  # docker:
-  #   - image: cimg/openjdk:11.0
-  # steps:
-  #   - checkout
-  #   - run:
-  #       name: Instalar SonarScanner
-  #       command: |
-  #         curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
-  #         unzip sonar-scanner-cli.zip
-  #         export PATH=$PATH:$(pwd)/sonar-scanner-4.6.2.2472-linux/bin
-  #   - run:
-  #       name: Ejecutar SonarScanner
-  #       command: |
-  #         sonar-scanner \
-  #           -Dsonar.projectKey=Continous-Integration \
-  #           -Dsonar.organization=sixtoarrejin \
-  #           -Dsonar.host.url=https://sonarcloud.io \
-  #           -Dsonar.login=$SONAR_TOKEN
+          custom: '{"text":"Se ha pasado el análisis de SonarCloud! :white_check_mark:"}'
 
   deploy:
     docker:
